---
apiVersion: v1
items:
- metadata:
    creationTimestamp: "2024-02-25T15:50:58Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "233"
    uid: eabcc611-35e3-4782-92a9-fa32e5eaf2af
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- metadata:
    creationTimestamp: "2024-02-25T19:31:53Z"
    labels:
      app: server-fever
    name: server
    namespace: default
    resourceVersion: "9722"
    uid: 0aaa880c-0dba-433f-9511-1b0f185644cb
  spec:
    clusterIP: 10.96.90.34
    clusterIPs:
    - 10.96.90.34
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: server-fever
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "136341"
