apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-fever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-fever
  template:
    metadata:
      labels:
        app: client-fever
    spec:
      hostAliases:
      - ip: "10.96.90.34"
        hostnames:
        - "server"
        - "server.example.com"
        - "server.local"
      containers:
      - name: client-fever
        image: r3sj3r/fever-prueba:c3
        command:
          - sleep
          - "3600"
