apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server-fever
  name: server-fever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-fever
  template:
    metadata:
      labels:
        app: server-fever
    spec:
      containers:
      - name: server-fever
        image: r3sj3r/fever-prueba:s5
        ports:
        - containerPort: 5000
