apiVersion: v1
kind: Service
metadata:
  name: server.example.com
  labels:
    app: server-fever
spec:
  selector:
   app: server-fever
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
